name: template_syntax
description: Template Syntax
version: 0.0.1

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.0.0
  angular_components: ^0.10.0
  angular_forms: ^2.0.0

dev_dependencies:
  angular_test: ^2.0.0
  build_runner: ^1.0.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  pageloader: ^3.0.1
  test: ^1.0.0
